kafka:
  actions:
    Put_a_record_on_AGS_topic:
      bootstrapServers: "localhost:9092"
      topic: "topic1"
    Put_a_record_on_PS_topic:
      bootstrapServers: "localhost:9092"
      topic: "log-topic"